// ================================================================
// FIX AGENT TYPES
// ================================================================
//
// Purpose:
// Defines input/output contracts for the Fix Recommendation Agent.
//
// Fix Agent proposes remediation only.
// It does not validate risk and does not execute actions.
// ================================================================

import {
  ConfigurationDiffOutput,
  ConfigurationReaderOutput,
  Incident,
  LogAnalyzerAgentOutput,
  RootCauseAgentOutput,
  SearchFixPlaybookOutput,
  SearchRunbookOutput,
  ServiceInventoryOutput,
  WorkflowStep,
  logService,
} from './index.js';

import { RunbookEstimatedTime } from './runbook.types.js';

// ================================================================
// FIX AGENT INPUT
// ================================================================

export interface FixAgentInput {
  // Original incident detected by the system.
  incident: Incident;

  // Output generated by Root Cause Agent.
  rootCauseResult: RootCauseAgentOutput;

  // Output generated by Log Analyzer Agent.
  logAnalysisResult: LogAnalyzerAgentOutput;

  // Current workflow step.
  currentStep: WorkflowStep;
}

// ================================================================
// FIX AGENT ARTIFACTS
// ================================================================
//
// Tool outputs collected by the Fix Agent.
// These are preserved for auditability and downstream agents.
// ================================================================

export interface FixAgentArtifacts {
  // Matching remediation playbooks.
  playbooks: SearchFixPlaybookOutput['playbooks'];

  // Matching operational runbooks.
  runbooks: SearchRunbookOutput['runbooks'];

  // Current service configurations.
  configurations: ConfigurationReaderOutput['configurations'];

  // Recent relevant configuration changes.
  configurationChanges: ConfigurationDiffOutput['changes'];

  // Service ownership and criticality metadata.
  serviceInventory: ServiceInventoryOutput['services'];
}

// ================================================================
// FIX AGENT OUTPUT
// ================================================================
//
// AI generated remediation recommendation.
// Risk Validator consumes this output before execution.
// ================================================================

export interface FixAgentOutput {
  // Short remediation summary.
  summary: string;

  // Primary recommended remediation action.
  recommendedAction: string;

  // Confidence score from 0 to 100.
  confidence: number;

  // Services impacted by the proposed fix.
  affectedServices: logService[];

  // Commands proposed for remediation.
  commands: string[];

  // Rollback or recovery steps if remediation fails.
  rollbackPlan: string[];

  // Post-fix verification steps.
  verificationSteps: string[];

  // Evidence linking fix to root cause and tool context.
  evidence: string[];

  // Risk hints for the Risk Validator.
  riskHints: string[];

  // Estimated remediation time.
  estimatedTime: RunbookEstimatedTime;

  recommendedRunbookId?: string;

  recommendedPlaybookId?: string;
}

// ================================================================
// FIX AGENT EXECUTION RESULT
// ================================================================
//
// Mirrors Log Analyzer architecture:
// 1. analysis = final AI recommendation
// 2. artifacts = tool outputs used by the agent
// ================================================================

export interface FixAgentExecutionResult {
  // AI generated fix recommendation.
  analysis: FixAgentOutput;

  // Tool outputs collected during recommendation.
  artifacts: FixAgentArtifacts;
}
