// ================================================================
// RISK VALIDATOR AGENT TYPES
// ================================================================
//
// Purpose:
// Defines input/output contracts for the Risk Validator Agent.
//
// The Risk Validator evaluates whether the remediation
// recommended by the Fix Agent is safe to execute.
//
// It does NOT execute actions.
// It does NOT generate fixes.
//
// ================================================================

import {
  Incident,
  WorkflowStep,
  FixAgentOutput,
  FixAgentArtifacts,
} from './index.js';

import {
  ApprovalPolicyOutput,
  MaintenanceWindowOutput,
  ImpactAssessmentOutput,
  MissingValidationOutput,
} from './riskAgentTools.type.js';

// ================================================================
// RISK VALIDATOR INPUT
// ================================================================

export interface RiskValidatorInput {
  // Original detected incident.
  incident: Incident;

  // AI recommendation generated by Fix Agent.
  fixRecommendation: FixAgentOutput;

  // Operational artifacts collected by Fix Agent.
  fixArtifacts: FixAgentArtifacts;

  // Current workflow step.
  currentStep: WorkflowStep;
}

// ================================================================
// RISK LEVEL
// ================================================================

export type RiskLevel = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';

// ================================================================
// FINAL DECISION
// ================================================================

export type RiskDecision = 'APPROVED' | 'REQUIRES_HUMAN_APPROVAL' | 'REJECTED';

// ================================================================
// RISK VALIDATOR ARTIFACTS
// ================================================================

export interface RiskValidatorArtifacts {
  approvalPolicy: ApprovalPolicyOutput;

  maintenanceWindow: MaintenanceWindowOutput;

  impactAssessment: ImpactAssessmentOutput;

  missingValidation: MissingValidationOutput;
}

// ================================================================
// RISK VALIDATOR OUTPUT
// ================================================================

export interface RiskValidatorOutput {
  // Overall validation summary.
  summary: string;

  // Calculated risk level.
  riskLevel: RiskLevel;

  // Risk score (0-100).
  riskScore: number;

  // Whether admin approval is required.
  approvalRequired: boolean;

  // Whether execution is considered safe.
  safeToExecute: boolean;

  // Possible impact if executed.
  potentialImpacts: string[];

  // Validation observations.
  validationFindings: string[];

  // Missing validation items.
  missingChecks: string[];

  // Recommended precautions.
  recommendedPrecautions: string[];

  // Final execution decision.
  decision: RiskDecision;

  // Reason for decision.
  reason: string;

  // AI confidence score.
  confidence: number;
}

// ================================================================
// RISK VALIDATOR EXECUTION RESULT
// ================================================================

export interface RiskValidatorExecutionResult {
  analysis: RiskValidatorOutput;

  artifacts: RiskValidatorArtifacts;
}
