// ================================================================
// ROOT CAUSE AGENT TYPES
// ================================================================
//
// Purpose:
// Defines all input/output types used by the Root Cause Agent.
// ================================================================

import {
  Incident,
  Log,
  DetectionAgentOutput,
  WorkflowStep,
  LogAnalyzerAgentOutput,
  LogAnalysisArtifacts,
} from './index.js';

// ================================================================
// ROOT CAUSE AGENT INPUT
// ================================================================

export interface RootCauseAgentInput {
  // Original incident detected by the system.
  incident: Incident;

  // Incident related logs.
  logs: Log[];

  // Detection Service output.
  detectionResult: DetectionAgentOutput;

  // Output generated by Log Analyzer Agent.
  logAnalysisResult: LogAnalyzerAgentOutput;

  // Tool outputs generated by Log Analyzer Agent.
  logAnalysisArtifacts: LogAnalysisArtifacts;

  // Current workflow step.
  currentStep: WorkflowStep;
}

// ================================================================
// ROOT CAUSE AGENT OUTPUT
// ================================================================
//
// AI generated root cause analysis.
// ================================================================

export interface RootCauseAgentOutput {
  // Final identified root cause.
  rootCause: string;

  // Why this root cause was selected.
  reasoning: string;

  // Confidence score.
  confidence: number;

  // Supporting evidence.
  evidence: string[];
}

// ================================================================
// ROOT CAUSE EXECUTION RESULT
// ================================================================
//
// Agent currently returns only AI analysis.
//
// Tools may be added later without changing
// the service or workflow architecture.
// ================================================================

export interface RootCauseExecutionResult {
  analysis: RootCauseAgentOutput;
}
