version: '3.8'

services:
  mongodb:
    image: mongo:7.0

    container_name: resolvix-mongodb

    restart: unless-stopped

    environment:
      MONGO_INITDB_DATABASE: resolvix-ai

    ports:
      - '27017:27017'

    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    restart: unless-stopped

    container_name: resolvix-backend

    env_file:
      - backend/.env.production

    ports:
      - '5000:5000'

    depends_on:
      - mongodb

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    restart: unless-stopped

    container_name: resolvix-frontend

    env_file:
      - frontend/.env.production

    ports:
      - '3000:3000'
    depends_on:
      - backend

volumes:
  mongodb_data:
