// ================================================================
// NOTIFICATION MODEL
// ================================================================
//
// Purpose:
// Stores system notifications generated by AI agents.
//
// Used by:
//
// - Notification Service
// - Dashboard
// - Notification APIs
//
// ================================================================

import { model, Schema } from 'mongoose';

import { Notification } from '../types/index.js';

// ================================================================
// Notification Schema
// ================================================================
const notificationSchema = new Schema<Notification>(
  {
    // ------------------------------------------------------------
    // Related Incident
    // ------------------------------------------------------------
    incidentId: {
      type: String,
      required: true,
      trim: true,
    },

    // ------------------------------------------------------------
    // Notification Title
    // ------------------------------------------------------------
    title: {
      type: String,
      required: true,
      trim: true,
    },

    // ------------------------------------------------------------
    // Notification Message
    // ------------------------------------------------------------
    message: {
      type: String,
      required: true,
      trim: true,
    },

    // ------------------------------------------------------------
    // Notification Severity
    // ------------------------------------------------------------
    severity: {
      type: String,
      enum: [`info`, `success`, `warning`, `error`],
      required: true,
    },

    // ------------------------------------------------------------
    // Notification Recipients
    // ------------------------------------------------------------
    recipients: {
      type: [String],
      required: true,
      default: [],
    },

    // ------------------------------------------------------------
    // Notification Status
    // ------------------------------------------------------------
    status: {
      type: String,
      enum: [`unread`, `read`],
      default: `unread`,
    },
  },

  {
    timestamps: true,
  },
);

// ================================================================
// Indexes
// ================================================================

// Recent notifications for an incident
notificationSchema.index({ incidentId: 1 });

// Latest notifications first
notificationSchema.index({ createdAt: -1 });

// Filter unread notifications
notificationSchema.index({ status: 1, createdAt: -1 });

// Filter by severity
notificationSchema.index({ severity: 1 });

// ================================================================
// Model
// ================================================================

export const NotificationModel = model<Notification>(
  'Notification',
  notificationSchema,
);
